version: '3'

services:
  react_app:
    container_name: react_app
    build: ./react
    #command: npm start
    volumes:
      - ./web:/app
    ports:
      - 3000:3000

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./web/build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - react_app