version: '3'

services:
  react_app:
    container_name: react_app_prod
    command: npm run build
  nginx:
    image: nginx
    container_name: nginx_prod
    ports:
      - 8080:80
    volumes:
      - ./web/build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - react_app